### ISSUE TITLE
i can't find your sortingProperty/sortItem function,where is your realization？

### ISSUE THREAD

**Issue by PPHAC** [lewisl9029/redux-data-table#1]

**Comment by lewisl9029** [comment]
You can find the definitions for `sortingProperty` and `sortItems` [here](https://github.com/lewisl9029/redux-data-table/blob/ea37e42824bf60569a88fee9212c002361c0620e/app/containers/app.jsx#L30-L31).

`sortingProperty` is just a string value in the app state where we store the property we're currently sorting on, while `sortItems` simply dispatches the `SORT_ITEMS` Redux [action](https://github.com/lewisl9029/redux-data-table/blob/ea37e42824bf60569a88fee9212c002361c0620e/app/actions/actions.js#L13-L16). 

The actual sorting logic is [here](https://github.com/lewisl9029/redux-data-table/blob/ea37e42824bf60569a88fee9212c002361c0620e/app/reducers/items.js#L15-L16) in the `items` reducer, in the case where it receives a `SORT_ITEMS` action. 

You can read more about actions, reducers and how data flow in general works in a Redux app in the official Redux [docs](http://redux.js.org/docs/basics/index.html). 

Hope that helps! Feel free to follow up if anything is still unclear.
